routes/web.php
<?php

use App\Http\Controllers\AdminProductsController;
use App\Http\Controllers\ShoppingCartController;
use App\Http\Controllers\SignOutController;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SignInController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\AddressController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;

use App\Models\Product;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', [HomeController::class, "index"])->name("home");

Route::get('/sign-out', [SignOutController::class, "index"])->name("sign-out");

Route::get('/login', [SignInController::class, "index"])->name("login");
Route::post("/login", [SignInController::class, "login"])->name("loginRequest");

Route::get('/products', [ProductController::class, "getAllProducts"])->name("products");

Route::get('/register', [SignUpController::class, "index"])->name("register");
Route::post('/register/create', [SignUpController::class, "register"])->name("register.create");

Route::get("/admin/products", [AdminProductsController::class, "index"])->name("admin.products");
Route::get("/admin/products/edit/{id}", [AdminProductsController::class, "editIndex"])->name("admin.products.edit");
Route::get("/admin/products/create", [AdminProductsController::class, "createIndex"])->name("admin.products.create");

Route::put("/products/{id}", [AdminProductsController::class, "editAction"])->name("admin.products.edit.update");
Route::delete("/products/{id}", [AdminProductsController::class, "deleteAction"])->name("admin.products.edit.delete");
Route::post("/products", [AdminProductsController::class, "createAction"])->name("admin.products.edit.create");

Route::get("/account", [SettingsController::class, "index"])->name("account");
Route::post("/account/update", [SettingsController::class, "update"])->name("account.update");

Route::get("/account/orders", [OrderController::class, "getAllOrders"])->name("account.orders");

Route::get("/account/orders", [OrderController::class, "getOrdersByUser"])->name("account.orders");
Route::get("/admin/orders", [OrderController::class, "getAllOrders"])->name("admin.orders");
Route::get("/admin/orders/approve/{id}", [OrderController::class, "approveOrder"])->name("admin.order.approve");
Route::delete("/orders/{id}", [OrderController::class, "deleteOrder"])->name("account.orders.delete");
Route::post("/orders", [OrderController::class, "createOrder"])->name("account.orders.create");

Route::get("/shopping-cart", [ShoppingCartController::class, 'index'])->name("shopping-cart");
Route::delete("/users/{userId}/shopping-cart/{productId}", [ShoppingCartController::class, 'deleteItemAction'])->name("shopping-cart.delete");

Route::get('/product/detail/{id}', [ProductController::class, 'getProductById'])->name("product.detail");

Route::get('/contact', [ContactController::class, 'index'])->name("contact");
Route::post("/shopping-cart/{productId}", [ShoppingCartController::class, 'createItemAction'])->name("shopping-cart.create");

Route::get("/account/address", [AddressController::class, "index"])->name("account.address");
Route::get("/account/address/create", [AddressController::class, "createView"])->name("account.create.address");
Route::post("/account/address/create", [AddressController::class, "saveAddress"])->name("account.create.address");

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'price',
        'quantity',

    ];

    public function getPriceAttribute($value)
    {
        return $value / 100;
    }

    public function setPriceAttribute($value)
    {
        $this->attributes["price"] = $value * 100;
    }

    public function getPivotTotalAttribute()
    {
        return $this->pivot->product_count * $this->price;
    }
}

app/Http/Controllers/ProductController.php
<?php


namespace App\Http\Controllers;


use App\Models\Product;
use App\Providers\ProductServiceProvider;
use App\Providers\Services\ProductService;

class ProductController
{
    public function getAllProducts(ProductService $productService)
    {
        $products = $productService->getAll();


        return view('pages.products', ['products' => $products]);
    }

    public function getProductById($id)
    {
        $product = Product::find($id);

        return view('pages.detail', ['product' => $product]);
    }
}

app/View/Components/FormField.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class FormField extends Component
{
    public $name;
    public $required;
    public $title;
    public $type;
    public $description;
    public $value;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($name, $required, $type, $title, $value = "")
    {
        $this->name = $name;
        $this->required = $required == 'true';
        $this->title = $title;
        $this->type = $type;
        $this->value = $value;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|string
     */
    public function render()
    {
        return view('components.form_field');
    }
}

resources/views/pages/admin/products/create-product.blade.php
@extends("layout.layout")
@section("page-title", __("pages.admin_products"))

@section("content")
    <div class="row">
        <div class="col-8 mx-auto">
            <form method="post" action="{{ route("admin.products.edit.create")  }}">
                @csrf

                @include('pages.admin.products.product-form')

                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/products/edit-product.blade.php
@extends("layout.layout")
@section("page-title", __("pages.admin_products"))

@section("content")
    <div class="row">
        <div class="col-8 mx-auto">
            <form method="post" action="{{ route("admin.products.edit.update", [$product->id]) }}">
                @csrf

                @include('pages.admin.products.product-form')

                @can('update', $product)
                    <input type="submit" name="_method" value="put" class="btn btn-primary">
                @endcan

                @can('delete', $product)
                    <input type="submit" name="_method" value="delete" class="btn btn-danger">
                @endcan
            </form>
        </div>
    </div>
@endsection

resources/views/pages/admin/products/product-form.blade.php
<div class="form-row">
    <div class="form-group col-md-12">
        <x-form-field :title="__('general.name')"
                      :value="isset($product) ? $product->name : ''"
                      required="true" name="name" type="text"></x-form-field>
    </div>
    <div class="form-group col-md-12">
        <x-form-field :title="__('general.description')"
                      :value="isset($product) ? $product->description : ''"
                      required="true" name="description" type="text"></x-form-field>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <x-form-field :title="__('general.price')"
                      :value="isset($product) ? $product->price : ''"
                      required="true" name="price" type="text"></x-form-field>
    </div>
    <div class="form-group col-md-6">
        <x-form-field :title="__('general.quantity')"
                      :value="isset($product) ? $product->quantity : ''"
                      required="true" name="quantity" type="number"></x-form-field>
    </div>
</div>
<div class="form-row">
    <div class="form-group">
        <div class="form-check">
            <input class="form-check-input" name="onSale" type="checkbox" {{ isset($product) && $product->on_sale ? 'checked' : '' }}>
            <label class="form-check-label">
                @lang("general.on_sale")
            </label>
        </div>
    </div>
</div>

resources/views/pages/admin/products/products.blade.php
@extends("layout.layout")
@section("page-title", __("pages.admin_products"))

@section("content")
    <div class="row">
        <div class="col-12">

            @can(['create'], \App\Models\Product::class)
                <a class="btn btn-primary" href="{{ route("admin.products.create") }}">@lang("general.create")</a>
            @endcan

            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th scope="col">@lang("general.id")</th>
                    <th scope="col">@lang("general.name")</th>
                    <th scope="col">@lang("general.price")</th>
                    <th scope="col">@lang("general.quantity")</th>
                    <th scope="col">@lang("general.on_sale")</th>
                    <th scope="col">@lang("general.actions")</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                    <tr>
                        <th scope="row">{{ $product->id }}</th>
                        <td>{{ $product->name }}</td>
                        <td>€ {{ $product->price }}</td>
                        <td>{{ $product->quantity }}</td>
                        <td>{{ $product->on_sale ? 'true' : 'false' }}</td>

                        <td>
                            @canany(['update'], $product)
                                <a href="{{ route('admin.products.edit', [$product->id])  }}">@lang("general.edit")</a>
                            @endcanany
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection